import Head from "next/head";
import { useContext } from "react";
import { DataContext } from "./MyContext";

const HeadMeta = ({ title }) => {

  return (
    <Head>
      <title> {title} </title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HeadMeta;
