import List from "@/List";
import Layout from "@/pages/src/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>title</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <List></List>
      </Layout>
    </>
  );
}
